function worldInit()
    -- World   
    world = wf.newWorld(0, 1000, false)        
    world:addCollisionClass("Attack")     
    world:addCollisionClass("BossAttack")
    world:addCollisionClass("Projectile")   
    world:addCollisionClass("Player", {ignores = {"Attack"}})  
    world:addCollisionClass("Platform")
    world:addCollisionClass("Wall")
    world:addCollisionClass("Ghoul", {ignores = {"Ghoul"}})
    world:addCollisionClass("EnemyHit", {ignores = {"Player"}})
    world:addCollisionClass("Wasp", {ignores = {"Player", "Ghoul"}})
    world:addCollisionClass("Hive", {ignores = {"Player", "Wasp"}})
    world:addCollisionClass("Spitter", {ignores = {"Spitter", "Ghoul"}})
    world:addCollisionClass("Summoner", {ignores = {"Summoner", "Spitter", "Ghoul", "Wasp"}})
    world:addCollisionClass("Boss", {ignores = {"Player", "BossAttack"}})
    world:addCollisionClass("Switch", {ignores = {"Attack", "Ghoul", "Wasp", "Spitter", "Summoner"}})
    world:addCollisionClass("Gate")
    world:addCollisionClass("Teleport", {ignores = {"Player", "Attack", "Ghoul", "Wasp", "Spitter", "Summoner", "EnemyHit"}})     
    world:addCollisionClass("Shop", {ignores = {"Player", "Attack", "Ghoul", "Wasp", "Spitter", "Summoner", "EnemyHit"}})
    world:addCollisionClass("Statue", {ignores = {"Player", "Attack", "Ghoul", "Wasp", "Spitter", "Summoner", "EnemyHit"}})
    world:addCollisionClass("Watcher", {ignores = {"Player", "Attack", "Ghoul", "Wasp", "Spitter", "Summoner", "EnemyHit" }})
    world:addCollisionClass("Level")
    world:addCollisionClass("GameWin")
    
    -- Add the projectile collision class (if you haven't already)   
end